num1 = 20
num2 = 10

print("num1", num1)
print("num1", num2)
print("Addition:", num1+num2)
print("Subtraction:", num1-num2)
print("Division:", num1/num2)
print("Multiplication:", num1*num2)
print("Square:", num1**2)
print("SquareRoot:", num2*0.5)
print("Equal To:", num1+num2)
print("Greater:", num1>num2)
print("Less:", num1>num2)

print("AFTER PRINTING ...........")
print("---------------------------------------")

result = num1*num2*0.5/2+num1
print("The result of the given equation is:", result)

