name = "Parth"
age = 11
weight = 35.6 
boolm = True

print("The value of name is:", name)
print("The data type of name is:", type(name))
print("The value of age is:", age)
print("The data type of age is:", type(age))
print("The value of weight is:", weight)
print("The data type of weight is:", type(weight))
print("The value of boolm is:", boolm)
print("The data type of boolm is:", type(boolm))

print("AFTER CASTING ............")
print("----------------------------------------")

age = str(age)
print("The value of age is:", age)
print("The data type of age is:", type(age))

weight = int(weight)
print("The value of weight is:", weight)
print("The data type of weight is:", type(weight))

boolm = float(boolm)
print("The value of boolm is:", boolm)
print("The data type of boolm is:", type(boolm))
